name: game
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+33

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.30.1
  stroke_text: ^1.0.0
  vibration: ^3.1.3
  shared_preferences: ^2.5.3
  flutter_confetti: ^0.5.1
  google_mobile_ads: ^6.0.0
  flutter_soloud: ^3.2.7
  flutter_dotenv: any
  games_services: ^4.1.0
  fluttertoast: ^9.0.0
  firebase_analytics: ^12.0.4
  firebase_core: ^4.2.1
  in_app_update: ^4.2.5
  permission_handler: ^12.0.1
  firebase_messaging: ^16.0.4
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#E9FCD9"
  image: assets/images/splash.png
  android_12:
    color: "#E9FCD9"
    image: assets/images/splash.png


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bird/
    - assets/audio/
    - .env